### PR TITLE
Support the new abs opcodes

### LINKED ISSUE #73: Does not recognize i8x16.abs, i16x8.abs, i32x4.abs
These opcodes were added recently and must be handled.

### PR DESCRIPTION
**Pull request by lars-t-hansen**
Fixes #73

### CODE REVIEW

**Comment by alexcrichton** [comment]
It looks like the version of wabt we're testing against has a version of the test suite which actually asserts that these opcodes specifically don't parse, hence the failling tests.

You can add some [exceptions here](https://github.com/bytecodealliance/wat/blob/d32db48426c712f5873fb82e47c559d123162a82/tests/wabt.rs#L439-L464) and mind leaving a comment to un-except the tests eventually once the updated tests in the spec repo percolate down?

**Comment by lars-t-hansen** [comment]
Will do that.

**Comment by alexcrichton** [comment]
Do y'all need a publish on your end as well?

**Comment by lars-t-hansen** [comment]
> Do y'all need a publish on your end as well?

I don't know precisely what you mean by that but yes, we need to pull this change into SpiderMonkey and it's possible we need a release for that pushed to crates.io.  @eqrion, opinions?

**Comment by alexcrichton** [comment]
Oh sorry yeah I mean to ask if you need a crates.io publish to pull in an update to SpiderMonkey or if y'all are using git dependencies or `[patch]` to pull in minor updates like this. In any case I went ahead and published a new version so y'all can update

**Comment by eqrion** [comment]
Thanks! Right now we're using crates.io to pull in updates for wat. In the future we can use git dependencies and `patch` but for now this has worked well.

**Pull request merged**
