### PR TITLE
Implement the MVP GC syntax

### LINKED ISSUE #72: Align GC syntax and encoding with WABT
V8 and WABT are implementing a subset of the GC proposal deemed the MVA. I believe we will be compliant on the text syntax front, as that's well documented in the MVP.md doc. The encodings aren't specified that I'm aware of, so that will need to be aligned.

[1] https://github.com/WebAssembly/gc/issues/81

### PR DESCRIPTION
**Pull request by eqrion**
Fixes #72. The encoding/syntax is derived from this [document]( https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit). There's no formal spec so things are expected to change, but the goal is compatibility with V8/wabt.

### CODE REVIEW

**Comment by alexcrichton** [comment]
👍

**Comment by alexcrichton** [comment]
Want a publish as well to pull this into gecko?

**Comment by lars-t-hansen** [comment]
> Want a publish as well to pull this into gecko?

We want to be sure that doesn't break anything, because we have users of the existing encodings.  (I know Ryan knows this, just sayin'.)

**Comment by eqrion** [comment]
@alexcrichton I've got the SpiderMonkey side figured out now. Would you be able to do an update?

**Comment by alexcrichton** [comment]
Sure thing, published!

**Comment by eqrion** [comment]
Thanks!

**Pull request merged**
